### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by stefvvn** [stefvvn/testpraksa2#1]
### Feed
- [x] reklame
- [x] login usera
- [x] setovanje cookia
- [x] prikazivanje usera u headeru
- [x] CSS za postove
- [ ] like za postove
- [ ] komentari
- [ ] like za komentare
- [ ] slike u bazi
- [ ] profile slike
- [ ] post slike
- [ ] slike u komentarima
